name: bexmovil
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  badges: ^3.0.3
  bloc: ^8.1.1
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.13.2
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  dart_ping: ^8.0.1
  device_info_plus: ^9.0.0
  dio: ^5.0.2
  dot_navigation_bar: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_datetime_picker: ^1.5.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^3.0.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.4
  flutter_udid: ^2.0.1
  font_awesome_flutter: ^10.6.0
  geolocator: ^10.1.0
  get_it: ^7.2.0
  google_sign_in: ^6.1.6
  google_sign_in_platform_interface: ^2.4.2
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  intl: ^0.18.0
  latlong2: ^0.8.1
  location_repository:
    path: packages/location_repository
  lottie: ^2.7.0
  meta: ^1.8.0
  path: ^1.8.2
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  pinput: ^3.0.1
  provider: ^6.1.1
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  showcaseview: ^2.0.2
  sqflite: ^2.2.6
  sqflite_migration: ^0.3.0
  sqlbrite: ^2.6.0
  syncfusion_flutter_calendar: ^24.1.41
  syncfusion_flutter_charts: ^24.1.41
  syncfusion_flutter_datagrid: 24.1.41
  syncfusion_localizations: ^24.1.45
  synchronized: ^3.0.1
  universal_platform: ^1.0.0+1
  upgrader: ^7.0.2
  url_launcher: ^6.1.10
  validators: ^3.0.0
  vibration: ^1.7.6
  yaml: ^3.1.1
  syncfusion_flutter_datagrid: ^24.1.44

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/launcher/
    - assets/animations/
    - assets/icons/
    - assets/data/
    - assets/lang/
    - pubspec.yaml
  fonts:
    - family: Butler
      fonts:
        - asset: assets/fonts/Butler_Bold.ttf
        - asset: assets/fonts/Butler_Light.ttf
        - asset: assets/fonts/Butler_Regular.ttf
    - family: IBM
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
        - asset: assets/fonts/IBMPlexSans-Light.ttf
        - asset: assets/fonts/IBMPlexSans-Regular.ttf

    - family: Benton
      fonts:
        - asset: assets/fonts/BentonSans-Regular.ttf
        - asset: assets/fonts/BentonSans-Black.ttf
        - asset: assets/fonts/BentonSans-Bold.ttf
        - asset: assets/fonts/BentonSans-Book.ttf
